# -*- coding: utf-8 -*-
"""forLoop

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qd_OQIvsC0UqDgV9u21_IwUhZFGJD5ll
"""

for car in "Hello World":
  print("tery sheer me naaam mera")

list = ["engineer","doctor","ca","business"]
for prof in list:
  print(list)

list = ["engineer","doctor","ca","business"]
for prof in list:
  print(prof)

print(range(0,6))

dic ={"k1":84,"k2":48,"k3":98}
for  k, i in dic.items():
  print(k)

dic ={"k1":84,"k2":48,"k3":98}
for   i in dic.items():
  print(i)

dic ={"k1":84,"k2":48,"k3":98}
for  k in dic.values():
  print(k)

dic ={"k1":84,"k2":48,"k3":98}
for  k in dic.keys():
  print(k)

for me in range(8):
  print(me)

var = "i am ankit"
let = 338308
print("{} and this is my no. {}".format("hi" , "hi"))

var = "i am ankit"
let = 338308
print(f"{var} and this is my no. {let}")

var = "i am ankit"
let = 338308
print("{} and this is my no. {}".format(var , let))

var = "i am ankit"
let = 338308
print("{1} and this is my no. {0}".format(var , let))

var = "i am ankit"
let = 338308
print("{v} and this is my no. {l}".format(v=var , l=let))

l1=[1,2,3,4,5]
l2=["a","b","c","d","e"]
for item in zip(l1,l2):
  print(item)

l1=[1,2,3,4,5]
l2=["a","b","c","d","e"]
for i, y in zip(l1,l2):
  print(i, y)

