# -*- coding: utf-8 -*-
"""List.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J9uAuvCkVZA_nzidDAFjrkvCD0q7KPJu
"""

list=['1','2','3','4','5']

print(list)

list[0]= 100

print(list)

list[2:4]

list[:5]

list

list.append('6')

list

list.pop()

list.pop(0)

firstVar=list.pop(0)

firstVar

list

list.reverse()

"""Does not return"""

list

list.sort()

list

dom=['r54','skyline,''supra',True, False,25]

dom

"""sort not work"""

