# -*- coding: utf-8 -*-
"""tuple.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SiBcNPRBoSvlJeIgtN2f8MtCibpaXt1j
"""

tup = (1,54,4,26,87)

len(tup)

tup[0]

tup[-1]

tup[2:9]

tup1 = ('one',2,'three',4,'five',6,'seven')

"""tuple can take multiple values"""

print(tup1);

tup1

tup1;

